services:
  postgres:
    image: postgres:16
    container_name: pulsar-postgres
    environment:
      POSTGRES_DB: pulsar
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5433:5432"
    volumes:
      - pulsar_postgres_data:/var/lib/postgresql/data

volumes:
  pulsar_postgres_data: